server:
  port: 8080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dwyane-Xu/examSys.git
          username: 502794297@qq.com
          password: hxfs43j8740
#          basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
#management:
#  endpoints:
#    web:
#      expose: "*"
