server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examSys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Hxfs43j8740@
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

# feign配置
feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
  hystrix:
    enabled:  true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ignore:
  urls:
  - /
  - /error
  - /favicon.ico
  - /**/*swagger*/**
  - /v2/api-docs
  - /csrf
  - /actuator/**
  - /hystrix.sender
  - /v1/sms/**
  - /v1/user/findUserByIdentifier/**
  - /v1/tenant/findTenantByTenantCode/**
  - /v1/user/checkExist/**
  - /v1/user/updatePassword
  - /v1/menu/findMenuByRole/**
  - /v1/menu/findAllMenu
  - /v1/code/**
  - /v1/attachment/download
  - /v1/log/**
  - /authentication/**
  - /v1/authentication/**
  - /**/*.css
  - /**/*.js
  - /social
  - /signin
  - /signup
  - /info
  - /health
  - /metrics/**
  - /loggers/**

# 系统配置
sys:
  adminUser: admin  # 管理员账号，默认是admin
  key: '1234567887654321'
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天