server:
  port: 8080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dwyane-Xu/config-repo
          username: 502794297@qq.com
          password: hxfs43j8740
#          basedir: /Users/xujinzhao/许锦钊/项目/毕业设计/examSys/config-service/src/main/resources/config
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
#management:
#  endpoints:
#    web:
#      expose: "*"